name: TeleSign
main: eu.andret.telesign.TeleSignPlugin
version: ${version}
author: Andret
api-version: '26.2'
description: Signs that teleport the player who clicks them to the coordinates written on them.
website: https://github.com/andret2344/TeleSign

commands:
  telesign:
    description: Reloads the TeleSign config.
    usage: /telesign reload
    aliases: [ tsigns ]
    permission: telesign.reload

permissions:
  telesign.*:
    description: Grants all TeleSign permissions.
    children:
      telesign.use: true
      telesign.create: true
      telesign.break: true
      telesign.reload: true
  telesign.use:
    description: Allows to be teleported by clicking a teleport sign.
    default: true
  telesign.create:
    description: Allows to create teleport signs.
    default: op
  telesign.break:
    description: Allows to break teleport signs.
    default: op
  telesign.reload:
    description: Allows to reload the config.
    default: op
